namespace: mysql-router
create_namespace: true

router:
  name: mysql-router
  service_name: mysql-router
  service_type: ClusterIP
  image: container-registry.oracle.com/mysql/community-router
  replicas: 1
  secret_name: mysql-router-bootstrap
  bootstrap_config_dir: /router
  expose_x_protocol: false

  bootstrap:
    user: root
    password: change-me
    host: mysql-node-0
    port: 3306
    extra_args: []

  storage:
    type: emptyDir

  probes:
    readiness_initial_delay_seconds: 10
    liveness_initial_delay_seconds: 30

nodes:
  - name: mysql-node-0
    ip: 10.10.1.11
    port: 3306
  - name: mysql-node-1
    ip: 10.10.1.12
    port: 3306
  - name: mysql-node-2
    ip: 10.10.1.13
    port: 3306
